### ISSUE TITLE
I cant read my irange 4+ module

### ISSUE THREAD

**Issue by jims1234** [benlye/dfu-util-multi#2]
I'm using flashmulti version 6.1
have tried multiple USB ports on two Win10 PC's and have two other MPM's that work Ok with my cable and I can Read/write  the mpm firmware in them both.  However, on my primary iRangeX 4+ module which has 20 planes bound to it.. I can't read the global ID yet as I update drivers, then update the bootloader using the DFU device which shows up Ok in Device manager.. I get a "done" message suggesting success.. after each attempt,  with no error but then I can't get past this... 
### I keep seeing : 
DFU Recovery Fail and then 
Filter on vendor = 0x1eaf product = 0x0003
Opening DFU capable USB device... ID 1eaf:0003
Run-time device DFU version 0110
Found DFU: [1eaf:0003] devnum=0, cfg=1, intf=0, alt=2, name="UNDEFINED"
Claiming USB DFU Interface...
Setting Alternate Setting #2 ...
Cannot set alternate interface

I have posted several screen dumps of the verbose sessions in Pascal's DIY MPM thread on RCgroups .com

all I need is to read the global ID  from this module. 

I've tried it many times with the USB-A to mini USB cable to a module IN a RM TS16S Radio that is turned OFF, as well as with the module alone on the end of my cable... If I need to get a TTS Serial to USB adapter, and solder the header and try again that way I will but do you think that might work?

**Comment by benlye** [comment]
The only time I've seen a message like that is with a bad USB hub.  Given that you've tried multiple PCs and cables I think you probably have a bad USB port on the module

Soldering the serial header pins on and using a USB-to-serial adapter will almost certainly work and should get you what you need.

**Comment by jims1234** [comment]
Hi Ben,

Thanks so much for the reply

 

Thank you for your  assessment and  guidance..

 

I’ve lost track of the header pins and the original doc sheet but found a diagram of the module pins . 

 

FDDI USB -to-serial TTL adapter I think I have one stowed with some Arduino stuff. And I’ll look for it now.

 

With your tip in mind I will try to using them..  once I find and connect it to the module 

 

I use FlaskMulti 6.x and my PC with this adapter.. or do I have to connect to my RM TX16S Radio’s pins as I have seen as an alternative? 

 

I want to use Flask Multi cause I know it’s Read Module option will help me find its  global ID

 

Thanks Again

JimS

**Comment by jims1234** [comment]
Will this one work?

https://www.amazon.com/Adapter-Serial-Converter-Development-Projects/dp/B075N82CDL/ref=sr_1_17_sspa?crid=3QWHJ4R9A05HP <https://www.amazon.com/Adapter-Serial-Converter-Development-Projects/dp/B075N82CDL/ref=sr_1_17_sspa?crid=3QWHJ4R9A05HP&dchild=1&keywords=usb+to+serial+adapter&qid=1619625126&sprefix=USB-to-serial+adapter+%2Caps%2C211&sr=8-17-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyQ1pQNjU1VkZJSFhGJmVuY3J5cHRlZElkPUEwNjY2NTU0T1czU0hGWVgzTE9MJmVuY3J5cHRlZEFkSWQ9QTA4NDI1MjIyQUJFMVpWWE1MQyZ3aWRnZXROYW1lPXNwX210ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=> &dchild=1&keywords=usb+to+serial+adapter&qid=1619625126&sprefix=USB-to-serial+adapter+%2Caps%2C211&sr=8-17-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyQ1pQNjU1VkZJSFhGJmVuY3J5cHRlZElkPUEwNjY2NTU0T1czU0hGWVgzTE9MJmVuY3J5cHRlZEFkSWQ9QTA4NDI1MjIyQUJFMVpWWE1MQyZ3aWRnZXROYW1lPXNwX210ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=

 

 

From: ***@***.*** ***@***.***> 
Sent: Wednesday, April 28, 2021 8:08 AM
To: 'benlye/dfu-util-multi' ***@***.***>; 'benlye/dfu-util-multi' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [benlye/dfu-util-multi] I cant read my irange 4+ module (#2)

 

Hi Ben,

Thanks so much for the reply

 

Thank you for your  assessment and  guidance..

 

I’ve lost track of the header pins and the original doc sheet but found a diagram of the module pins . 

 

FDDI USB -to-serial TTL adapter I think I have one stowed with some Arduino stuff. And I’ll look for it now.

 

With your tip in mind I will try to using them..  once I find and connect it to the module 

 

I use FlaskMulti 6.x and my PC with this adapter.. or do I have to connect to my RM TX16S Radio’s pins as I have seen as an alternative? 

 

I want to use Flask Multi cause I know it’s Read Module option will help me find its  global ID

 

Thanks Again

JimS

**Comment by benlye** [comment]
FT232RL-based adapters can be variable as there are quite a few fakes.  I tend to prefer CP2102-based devices, like this one:
https://www.amazon.com/HiLetgo-CP2102-Converter-Adapter-Downloader/dp/B00LODGRV8/

The easiest way to flash it is to use the 3V3 connection from the USB-to-serial adapter to power the module, then you don't need to have it powered up in the radio.

You will also need a couple of jumpers so that you can put the module into BOOT0 mode for flashing.

**Comment by jims1234** [comment]
Ben

Thanks I will try to cancel the 2 orders I placed at Amazon and e-Bay and get this particular one you linked ( it’s on order now too).. 

 

This is my module ( attached)  .., it seems to be a iRangeX IRX4 Plus STM32  and match the one shown in your doc page:

 

 

I’m looking carefully at:

https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/Compiling_STM32.md#connect-the-module

 

and it doesn’t really match any of the photos very well..

 

But the Photo title Bangood 4 –in- 1 is close and I can see the BOOT 0 jumper and the GND. TX. RX and Vin pins in the top left..

 

Some of these questions may be explained some where else in your doc files but I’ve missed them and just want to be sure..

 

Questions:

1.	Can I try to Read it with FlashMulti 6.1 once I connect the iRangeX  to my PC?
2.	Can I do this OUTSIDE of my Txmitter with this IRX4 Plus module connected via  the CP2102 adapter and jumpered to  the pins in the top left? 
3.	If so does the iRangeX  need the USB Adapter to be in the +5.0 or the +3.3 position to get power?  And Once powered will GRN LED be ON constantly? 
4.	At any point do I need to press the “ Bind “ button on the outside back of the module?
5.	I assume it is a Serial Interface (not PPM)
6.	And should be programmed with the Yellow rotatable Switch in it’s normal “0” position. 
7.	Should I also:

Bridge the BOOT0 pin to the adjacent 3.3V pin as shown by the yellow jumper. If it doesn't work move the jumper to bridge the two left hand pins (BOOT0 and directly above).

 

Thanks Again Ben..

V/r jimS

**Comment by benlye** [comment]
> 1.	Can I try to Read it with FlashMulti 6.1 once I connect the iRangeX  to my PC?

Yes.

> 2.	Can I do this OUTSIDE of my Txmitter with this IRX4 Plus module connected via  the CP2102 adapter and jumpered to  the pins in the top left?

Yes.

> 3.	If so does the iRangeX  need the USB Adapter to be in the +5.0 or the +3.3 position to get power?  And Once powered will GRN LED be ON constantly?

You must use 3.3V. Using 5V will destroy the module. The green LED should be on and the red LED should be off. If the red LED comes on then the BOOT0 jumpers are in the wrong position.

> 4.	At any point do I need to press the “ Bind “ button on the outside back of the module?

No

> 5.	I assume it is a Serial Interface (not PPM)

Yes, it's serial.

> 6.	And should be programmed with the Yellow rotatable Switch in it’s normal “0” position.

It shouldn't matter, but yes, keep it at 0 so that if the module starts up there is no chance it will start transmitting.

> 7.	Should I also: 
Bridge the BOOT0 pin to the adjacent 3.3V pin as shown by the yellow jumper. If it doesn't work move the jumper to bridge the two left hand pins (BOOT0 and directly above).

Yes, you must bridge the BOOT0 pins.  I have had most success using two jumpers, placed on the two left-most pairs of pins in the 6-pin block, like this `||:`

**Comment by jims1234** [comment]
Awesome…

I’ll do it.. the USB to serial adapter should be here in a couple days and I’ll let you know soonest..

Thank you very much for answering this long quiz..  I’m pretty confident I can set it up properly now..

Regards,

jimS

**Comment by jims1234** [comment]
Ben

The adapter arrived..  it’s the correct one in the link you sent me

I hooked it up and it didn’t work.

 

I put a 4 Pin header on the top left  and used two short U Shaped pieces of solder to make the two vertical jumpers.. ( per step 7 below)

 

I looked at the Photo in the doc file on github that looks the closest to a JP 4IN1 ..none of the photos match my module.   mine  is the IRANGEX 4 PLUS

But I followed the color coding and pin outs in that Jumper module photo could it was the best doc I found on the connection.

 

First thing I noted was that neither LED in the module ever came on .. but I figured it might be because it gets +5vdc when it’s plugged into a Radio and needs +5 and I think I’m only feeding it 3.3..

 

The Device Manager detects the adapter and sees  as a COM 5 port  but “Adapter 1 Fail” shows  the errors I got ( attached) ..

 

I did also try swapping the Tx and the RX pair at one end so that TX would be connected to Rx and vs versa.. but that did not help or change the two errors I see here as I try to install the drivers.. 

 

Any  thoughts? 

 

V/r jimS

  

  

 

 

From: ***@***.*** ***@***.***> 
Sent: Thursday, April 29, 2021 5:43 AM
To: 'benlye/dfu-util-multi' ***@***.***>; 'benlye/dfu-util-multi' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [benlye/dfu-util-multi] I cant read my irange 4+ module (#2)

 

Awesome…

I’ll do it.. the USB to serial adapter should be here in a couple days and I’ll let you know soonest..

Thank you very much for answering this long quiz..  I’m pretty confident I can set it up properly now..

Regards,

jimS

**Comment by jims1234** [comment]
I just realized that I should check and make sure the 3.3v is making it to the module’s Vss and GND pins.I’ll do that 1st. 

1. Is the layout for this boards BOOT same as yours and pins correct? 

2. Is there a schematic that matches this module? 

3. Should I try loading and using Zadig? Or are we past that since Windows does recognize it correctly 

Regards,
JimS 
***@***.***
Sent via cox.net from my iPad Pro

**Comment by benlye** [comment]
I was wrong about the LEDs - when wired correctly for flashing neither LED will not come on at all.

I have an iRangeX IRX4.  It's like yours but does not come with the bind button or LEDs. I soldered two LEDs and a USB port onto my module.  It's the same PCB though.

The connections on the 4-pin header should be (top to bottom):
GND
TX
RX
Vin

If you wire it up and only put a jumper on the middle pair of pins in the six-pin block (labelled 3V3) the module should power up and boot normally - green LED on and red LED flashing.  If you power it off, add the jumper to the left-most pins, then power it on, the module will be in BOOT0 mode with no LEDs on.

If you're sending pictures, they're not coming through.  Can you try adding them in Git directly (rather than replying to the email),

Here are some pictures of my wiring.  When connected like this I had no trouble reading the module.
![IMG_20210430_073908 (Medium)](https://user-images.githubusercontent.com/23322579/116658905-a2fbf600-a988-11eb-85c5-d3a25f3a8b78.jpg)
![IMG_20210430_073936 (Medium)](https://user-images.githubusercontent.com/23322579/116658906-a3948c80-a988-11eb-82d7-db622335ad9b.jpg)
![IMG_20210430_073941 (Medium)](https://user-images.githubusercontent.com/23322579/116658907-a3948c80-a988-11eb-86fd-6ad35ed92769.jpg)
![IMG_20210430_073952 (Medium)](https://user-images.githubusercontent.com/23322579/116658909-a42d2300-a988-11eb-942d-da28b674533a.jpg)

**Comment by jims1234** [comment]
Oddly I can’t send this from my Outlook client .. it’s stuck in the outbox there..

———————

Ben
1st off I really do want to thank you very much for walking me thru this.. 
 
Sadly I’m afraid that its looking more and more like the module I have has failed hard..and I’ll been to switch to my second IRANGE 4Plus that works, and rebind all my models.. I did order a 4th IRANGEX 4Plus module yesterday from Banggood but it’s likely a few weeks in transit   
 
I  will try to post the photos on github soonest..   but basically I did verify the Vin across that pin and GND at the module end is 3.3 vdc as it should be.
 
Also based on your photos,  I can see that Tx on one end should be wired to Rx on the other and I did confirm that transposition on both sides.
 
I don’t have the header pins ( which are smaller that the I/O pin spacing) so have been using needle nose pliers and short U shaped segments of solder instead.
I tried several jumper combinations on the two left jumpers and when I pulled out the one on left and left the middle one IN,  I get a steady GRN and then quick series of RED flashes  following that I see GRN ON but I never get the state needed which is GRN ON and  RED OFF,   Instead the RED LED that is flashing .5 seconds ON and .5 Seconds OFF and in that state I can’t read or  install drivers..
 
IF I put in the left jumper alongside ( with 2 installed) or have the Left Jumper alone in place I don’t get either LED to come ON on the module
 
In the USB Serial adapter end… there is a single RED LED that does typically  come ON steady,  but when the module is Flashing RED with GRN On always.. typically it is off..
 
Thanks again ,
jimS

Regards,
JimS 
***@***.***
Sent via cox.net from my iPad Pro

**Comment by jims1234** [comment]
Pls delete the msg just prior.. due to typos in it..

Regards,
JimS 
***@***.***
Sent via cox.net from my iPad Pro

**Comment by jims1234** [comment]
Ben,
I'm getting pretty frustrated now since I kept failing to Read and/or install drivers with my primary module and decided I should try it with a DIFFERENT IRANGEX 4Plus module that Did once work and that I was able to Read the global Id and to flash it with a pre-compiled firmware update.. but now with either the USB to Serial adapter wired per your photos, and with that removed and a normal USB-A to micro cable, using either my laptop or my normal Win 10 PC I can't access the module any more.. Win10 sees it as  a MAPPLE DFU device on the port , I refresh and see it as a DFU Device in FlashMini 6.1 then try to read it and it can't attach to it and When  I run thru the Install Drivers sequence again I never get the RED LED to stay OFF.. it just blinks every 1/2 second..with GRN Constantly ON.
This is ridiculous.. now both basically are doing the same thing on two different Pc's either with the straight USB cable or the the USB Serial adapter.. I don't know what to do next .. I tried with the BOOT0 jumper in either position and or both.. and re-installed FlashMulti.. here is a screengrab of the error:
 
![new error w previously working module](https://user-images.githubusercontent.com/13187800/116729939-aef1b300-a99c-11eb-9f16-0ce31b7618d8.jpg)

**Comment by benlye** [comment]
Ah. From the screenshot I can tell that you have the wrong DFU drivers installed.

Instructions for fixing them are here:
https://github.com/benlye/flash-multi/blob/master/doc/Troubleshooting.md#re-installing-the-maple-dfu-device-drivers

I think you should use the second approach and replace the driver with Zadig.

**Comment by jims1234** [comment]
Ben,
I could set up a Zoom or Discord video conference with a webcam and show you exaclty what’s I’m apparently doing wrong .. I’m in California and I assume you’re in France or UK ? So if you want to do this let me know when is a good local time there for me to try reaching you via zoom invite?  I need a little advance notice tho because I put the modules back in the radio to go flying.

If you’ve had enough.. that’s  fine too .. I’m sure you have better things to do..
Thanks again.. JimS

**Comment by jims1234** [comment]
Ok I’ll try again.. thanks Ben

Regards,
JimS 
***@***.***
Sent via cox.net from my iPad Pro

**Comment by jims1234** [comment]
Using my previously working "spare" on a new USB cable and my Win10 PC, I went thru Option 1 at the link you just provided and it failed again..so I tried to replace the Mapple driver using Zadig Option 2 and that did change the Windows 10 dirver I see in Device manager to a Multiprotocol type but I still cant read the module so I looked down further and saw where you're asked to go to a cmd prompt and run flashmulti from C:\Program Files (x86) .. my Flash multi was NOT installed there so I re-installed it there and re-ran it from that directory.. Tried to Read the module there .. no luck, tried to re-install the Module's USB drivers and Bootloader there and that did not work either..I have been unplugging the module from the USB cable after each step and re-plugging it back in..  I never so see the state required with a GRN LED On and RED Off.. mine always flashes the RED LED at a slow .5 sec ON/OFF rate.. I can send lots of screen dumps showing the result of each step is you want them.. do you?   but this last called "Nope" shows it's current state.. I also added a display of a USB Port logger at the bottom..  What next? I have a 4th module on order and haven't messed with the third one at all... its a Jumper JP4IN1SE.. 
![Nope ](https://user-images.githubusercontent.com/13187800/116790665-6d2f3e00-aa6a-11eb-9fa5-9bc7ef58287f.jpg)

**Comment by jims1234** [comment]
Ben,
you're off doing more important things.. but I just wanted to recap where this effort stands.. I've got two of these iRangeX 4 Plus MPM Modules and a JP4IN1 SE. The one I call my Primary works operationally ON -AIR but I can't use with FrSky Rx's since ever since I updated it last about 3 months ago I get a Trainer Signal Lost / Trainer signal recovered" audible cycling about every 5 seconds yet the Wireless signal is fine, and so I want to swap it out to try to fix that.. It has about 20 models bound to it so I need that global ID in it but have now tried a Desktop and Laptop with slightly different versions of Windows10 64 bit Pro s/w and driver sets in them. I've tried reading both irange 4plus modules, a new USB cable, re-installing using Zadig 3.5 and got a Successful notice and see a new MultiModuleDFU Bootloader notice you see immediately above here.. But I still can't use flashmulti 6.1 to read either module on either PC with either cable. I have tried using USB serial adapter in line with the Primary module too but not lately.. should I hook it back up to my Spare irange and try with that thing instead of the USB cable? I have another iRangeX 4Plus on order but it'll be a week+ from banggood minimum. I have the JP4IN1 SE as well but it has a RED LED that never comes on..I should probably return it.  Conversely with the two iRAnge 4Plus units I know I need to enter a state which I haven't seen in a month where the GRN LED is constantly ON and the RED is OFF but none of my MPMs enter this state.. One odd thing i noticed is that one of them has a male pin on the antenna connector mounted in the module, and the other irange has a female.. but this has nothing to do with reading that global ID. 
Should I try reading that ID again on the JP4IN1 SE.. it, and the SPARE iRANGE4Plus did both read and write a precompiled firmware image before I started, but the iRanges are both useless to me now ( except I still fly with the primary all the time) and I'm hoping that once the new Irange4 plus comes In that it's got a compatible bootloader installed in it and that I can use it, if need be by rebinding all my receivers to it.. as long as I can read it's global Id and write a compiled image to it I feel it's safe to proceed.. and I'll get a 5th one as a spare.  I'm sorry for this big hassle.

**Comment by benlye** [comment]
I'm running out of ideas and really not sure why this isn't working.  Something on your system is stopping the tools from talking to your module.

For reference, this is what the output should look like:
```
Filter on vendor = 0x1eaf product = 0x0003
Opening DFU capable USB device... ID 1eaf:0003
Run-time device DFU version 0110
Found DFU: [1eaf:0003] devnum=0, cfg=1, intf=0, alt=2, name="STM32duino bootloader v1.0  Upload to Flash 0x8002000"
Claiming USB DFU Interface...
Setting Alternate Setting #2 ...
```

See how the 'name=' line in mine says `name="STM32duino bootloader v1.0  Upload to Flash 0x8002000"` but yours says `name="UNDEFINED"`?  This means something is stopping the flashing tools communicating properly with the module.

Possible causes:
* Wrong driver (but you have the libusbk driver now, so that shouldn't be it)
* libusb DLL version
* Antivirus software
* Cables, ports, USB hub
* Something else

Do you have the module plugged *directly* in to your computer or via a USB hub?  If via a hub, try plugging in directly.  Can you double check that all the files are being extracted from the .zip file archive?  You should have files named libusb0.dll and libusb-1.0.dll in the \tools folder.  Can you try disabling any antivirus software you have?

Your JP4IN1 module works completely differently from a PC interface point of view, and you should be to read that as it uses a different tool (it's like using the USB-to-serial adapter).

**Comment by jims1234** [comment]
Ben,
I’ve got access to a 3rd Pc later today and will try it there and let u know .. 

Sent from my iPhone7Plus😄😄
619 708-7581 cel. ***@***.***

**Comment by jims1234** [comment]
Ben, After seeing both my PCs fail with it....I had a chance to take my "SPARE" IrangeX 4 PLUS over to someone's house with a 3rd PC and altho initially it failed too.. I was able to get the correct Win10 "Multiprotocol" USB driver onto it and try to update the module USB drivers again and that failed too except this time I figured what the hell.. and at the point it said I did not plug in the module fast enough ( right after the prior step where it says to wait until the RED LED goes out..( and mine never does) I tried it again and unplugged it anyway.. It failed with a warning " do not unplug the module" but this time when I plugged it back in, and it showed me an option to "Reset" the thing.  I noticed BOTH LED's were Off ( something I never see) and as I tried reinstalling the USB Module drivers again...I'll be darned.. it worked.. I could then read and see the global ID and would have re-installed a precompiled binary too except it already had the latest version.. 

I brought this now working "Spare"  module back home  and I was shocked to see I could still read it Ok on my main PC but... NOT on my laptop,, I tried to reprogram it but it failed and it now sees a Yellow sticky error in the laptops Win10Dev Manager under the libsyn.. 

I then switched to the Primary IRX 4+ Module and found I can't read it with either PC .. so I plan to wait till the brand new second SPARE arrives, ( sadly Expected delivery date is:  2021-05-26) make sure I can read and write to it OK then compile a custom DIY version with a new unique global ID.. and make both SPARE module's firmware match 100%, then bite the bullet and start the long process of rebinding all my planes to a new Primary with a duplicated global ID in it since I can't get my current one to read at all.   

I saved screen dumps of the entire process if you want to see them.. do you?

**Comment by jims1234** [comment]
Hi Ben

Here’s an update, as of noon Tuesday 5/11/2021 here..   there’s good and bad news.

I now have 4 MPM modules now, the JP4IN1 SE I can read nut set aside since it has a BAD RED LED.  the Primary daily driver I fly with… I was NEVER able to read it’s Global ID with the USB port on it or the TTL to USB Serial adapter so I set it aside too..  knowing I will need to re-bind all my models as I transition to a new spare. 

  

But the good news is I got the new “Spare No2” iRAngeX 4Plus module in the mail yesterday and it does connect and I can Read and Write to it using ONE of my two PC’s ( the laptop).. the other one / ( my Main Desktop) always sees it as a COM:x  port in Device manager so I couldn’t Read the Spare 2 module there, yet I can re-compile source code MOM code there on that PC, and since I was doing all my Arduino Edits and compiles on that Main PC too.. After trying  two cables and two different USB I/O ports  and tried about 50 times to Update the Drivers as well as update the Bootloader  but something blocks use of FlaskMulti  on that PC..

 

So I moved to the Laptop PC and found I can read and write BOTH modules with FlashMulti 6.1 Ok there 

 

So I just spent a couple hours editing the Global ID into the source _Config.h file to match the same 0x7647EE2D global ID already in the Spare 1 module, and I compiled it after commenting out many un-needed protocols and it re-compiled without error,  and I was successful in writing that firmware to the Spare 1 and reading the identical global ID back .. so I was ready to do the same and program the same custom firmware into Spare 2 the same way..   however..

 

I tried to re-compile again on the main desktop PC two separate times. I’d copy the .bin file and e-mail it as an attachment to the laptop then use the .bin attachment as the source and use FlashMulti (instead of the Arduino IDE compiler) to write it into the module) and I’ll be darned it does the same thing every time I have tried so far.. it Writes the new .bin file and I can read it with Flash Multi but the Global ID is the original.. it’s not the new Global ID I put into the source code as I deleted the comment slashes.. and updated the 0x12345678 that was there originally 

 

So since something odd is going on with my compile and transfer process I will .. go to the laptop, update it to the same version Arduino  IDE as is on the Desktop, try again to copy the source files over via e-mail of thumbdrive, ( or get a fresh copy and start from scratch)..  Recompile it there and hook up the Spare 1 then Spare2 modules while there on the laptop and update the firmware in them both directly..

 

I tried to move the source over earlier and had zipped and unzipped all the many many MPM files into a folder, but once I got all these within that folder un-zipped and moved into the laptop .. I don’t know how to make the IDE read the entire MPM project in to compile the whole thing, it seems to ONLY want to accept ONE .ino file at a time..

 

So I’m getting closer.. Its been one heck of a struggle tho. 

Thanks 

jimS

**Comment by jims1234** [comment]
Ben,
I moved to the laptop ( which does appear to work with FlashMulti 6.1 now)  and updated the IDE to the latest rev as well as loaded the STM 4 in 1 with the Boards manager and was able to re-download the STM Source file, open the _Config.h file and tweak the the Global ID with a new and different Global ID.  This ID and all the modules do appear to me to compile correctly, and I appear to be able to connect the module and "UPLOAD it into either of the two spare modules I have but when I re-read either of them .. the Global ID is NOT changed.

I also tried to export the .bin file from the compilation and I tried to use FlashMulti to write it instead and I can Write to the module, it says it's successful, but when I write the .bin file that is the compiled output of the MPM source code with my different/modified global ID and re-read it back.. I find that it's not changing from what it's always been from the factory.. 

So:
1.) either my compiled output is incorrect and never picking up the uncommented FORCE Global ID Definition line or
2.) the IDE Upload is not Uploading it into the module(s) properly, or 
3.) If I am creating a good .bin file and see Write Successful in FlashMulti.. the .bin file is not actually updating the global ID for some TBD reason..
or there is something else I am missing..  What do you think it is?

 As I use the IDE to Upload I do see an "UNrecognized USB device error " but am not sure if this is "normal"  I see a row of progress hashmarks that looks like it's writing OK, and a "Done" notice..
 As I use Flash Multi after using the module with as a COM port with the IDE I do need to Update the Drivers each time to get the DFU Device drivers set up on both sides before I can either Read or Write to either module.. but it too says it's successful when either reading or writing..  This stuff is so frustrating to be so near yet so far after coming this far... 

Any thoughts? 
jimS

**Comment by benlye** [comment]
When you read the module using Flash Multi it will only ever tell you the global ID which is stored in the EEPROM (which is based on the unique ID of the STM32 chip), it will never tell you one which you have specified in the config file as an override - there's no way to pull that out of the firmware image file, and it's not stored in the EEPROM.

If you have compiled firmware with a hardcoded ID and written that firmware to the modules you should be all set.

**Comment by jims1234** [comment]
Really!

 

Wow ..I’ll flash my FORCED  Global ID  again into both Spare 1 &2 since I last set then to different Forced ID’s then  I’ll plug them in to my Radio one at a time with a couple newly-bound planes and test this to be sure either can control it..

 

.. I have always assumed that once you force a new global ID that you should then be able to read it with your utility..

 

Is there an easy way to compare two .bin files and or two “Backups” I saved with flash multi and be certain they are identical? 

 

Also,  since I’ve been at this now for soooo long .. Before I give up on the original/ Primary iRANGX 4Plus I’m flying with now..  if I were able to read it using FlashMulti using the Serial TTL to USB adapter

Would reading that Global ID that’s in it’s EEPROM do me any good?    Note:   I have flashed it successfully back over a year ago with a precompiled binarywith FlashMulti 5.0, but never forced an new Global ID in to it.  and since the rebind process is risky and very time consuming  I wonder if it’s worth trying to get it out using Flash Multi and the USB Serial ADAPTER one last time.. or not?

 

Thanks again for your help in this effort Ben..

Regards 

jimS

**Comment by jims1234** [comment]
BTW : I found a good utility to do HASH compared on selected files.. it’s  CHK.exe

 

From: ***@***.*** ***@***.***> 
Sent: Wednesday, May 12, 2021 4:50 AM
To: 'benlye/dfu-util-multi' ***@***.***>; 'benlye/dfu-util-multi' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [benlye/dfu-util-multi] I cant read my irange 4+ module (#2)

 

Really!

 

Wow ..I’ll flash my FORCED  Global ID  again into both Spare 1 &2 since I last set then to different Forced ID’s then  I’ll plug them in to my Radio one at a time with a couple newly-bound planes and test this to be sure either can control it..

 

.. I have always assumed that once you force a new global ID that you should then be able to read it with your utility..

 

Is there an easy way to compare two .bin files and or two “Backups” I saved with flash multi and be certain they are identical? 

 

Also,  since I’ve been at this now for soooo long .. Before I give up on the original/ Primary iRANGX 4Plus I’m flying with now..  if I were able to read it using FlashMulti using the Serial TTL to USB adapter

Would reading that Global ID that’s in it’s EEPROM do me any good?    Note:   I have flashed it successfully back over a year ago with a precompiled binarywith FlashMulti 5.0, but never forced an new Global ID in to it.  and since the rebind process is risky and very time consuming  I wonder if it’s worth trying to get it out using Flash Multi and the USB Serial ADAPTER one last time.. or not?

 

Thanks again for your help in this effort Ben..

Regards 

jimS

**Comment by jims1234** [comment]
Ben

I can hardly believe what just happened.. but 1st let me update you with this..

 

On the laptop that has been working with FlashMulti lately,  I updated the Arduino IDE with the new version and set a unique but different global ID in __config h, then compiled it and used flash multi to install its resultant .bin file in BOTH spare Modules No 1 and 2 and tested binding them both with an ASSAN Rx and a FrSky D16 Receiver.. and I was able to toggle power OFF on the alternate Radio and retain the bind status properly using either Radio to both types of receivers.. Test Passed..  Yea!  So I’m now comfortable re-binding ALL my planes knowing that if I have a failure of either Spare 1 or Spare 2 I can swap it out

 

But 1st I decided to read my Primary Module that is currently bound to all my planes..one last time..

And I’ll be darned but after re-installing drivers on both sides  ( PC and Module). it worked and I was able to read the EEPRPM Global ID 0x123xxxx and save a backup of it

 

So my  question is: ..

 

1.	If I simply plug that ID in the source code and use it as a new Forced Global ID into the _Config.h and re-compile and it .. will the current BIND  work with all my modules without need to re-bind them , assuming that I also plug in the same Pre-compiled custom .bin with this duplicated Global ID that has been in this original / Primary iRangeX 4Plus,  and that hasn’t worked thru 100+ prior attempts till now..

 

If not what,  am I missing? 

 

2.	I haven’t tried Writing to this working Primary module yet but who knows it might actually work now on this laptop, ,it is an older release several versions bacl.. so should I update that firmware in it first then tru to clone it using flashmulti into the other two Spares?  .

  

  

     

 

From: ***@***.*** ***@***.***> 
Sent: Wednesday, May 12, 2021 6:07 AM
To: 'benlye/dfu-util-multi' ***@***.***>; 'benlye/dfu-util-multi' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [benlye/dfu-util-multi] I cant read my irange 4+ module (#2)

 

BTW : I found a good utility to do HASH compared on selected files.. it’s  CHK.exe

 

 

From: ***@***.*** ***@***.***>  ***@***.*** ***@***.***> > 
Sent: Wednesday, May 12, 2021 4:50 AM
To: 'benlye/dfu-util-multi' ***@***.*** ***@***.***> >; 'benlye/dfu-util-multi' ***@***.*** ***@***.***> >
Cc: 'Author' ***@***.*** ***@***.***> >
Subject: RE: [benlye/dfu-util-multi] I cant read my irange 4+ module (#2)

 

Really!

 

Wow ..I’ll flash my FORCED  Global ID  again into both Spare 1 &2 since I last set then to different Forced ID’s then  I’ll plug them in to my Radio one at a time with a couple newly-bound planes and test this to be sure either can control it..

 

.. I have always assumed that once you force a new global ID that you should then be able to read it with your utility..

 

Is there an easy way to compare two .bin files and or two “Backups” I saved with flash multi and be certain they are identical? 

 

Also,  since I’ve been at this now for soooo long .. Before I give up on the original/ Primary iRANGX 4Plus I’m flying with now..  if I were able to read it using FlashMulti using the Serial TTL to USB adapter

Would reading that Global ID that’s in it’s EEPROM do me any good?    Note:   I have flashed it successfully back over a year ago with a precompiled binarywith FlashMulti 5.0, but never forced an new Global ID in to it.  and since the rebind process is risky and very time consuming  I wonder if it’s worth trying to get it out using Flash Multi and the USB Serial ADAPTER one last time.. or not?

 

Thanks again for your help in this effort Ben..

Regards 

jimS

**Comment by jims1234** [comment]
Ben, 
Yes I now understand I’ll only ever read the hard coded ID and I can’t change that,, yes..

But what I’d like you to please confirm is this .. if I put in that Identical EEPROM Global ID from my Primary module into the Force Global ID field of the current source codes _Config.h uncomment, recompile then  export that .bin file then write it into my three iRange Plus modules, will they all work without any need to re-bind the Receivers in my planes? that has been the goal I’ve been seeking all along .. is that also your definition of being “all set.” If so I’d dearly love to end this saga and will try it right away.

**Comment by jims1234** [comment]
Ben, 
nevermind,, I tried it and it worked so I now have three iRAngeX 4Plus modules all flashed with the original Global ID and that all work with the latest x.x.x.77 version without re-binding my planes. Thanks so much for your patience and assist thru this ordeal.. I've never figured out why the drivers were installed correctly on BOTH the desktop PC and the Module side but something is blocking the READ in that PC even after successful "Done" driver installations.. but I'm sure glad it worked out and thank you again for walking me thru it.. Please feel free to close the issue.. There were several lessons learned but even tho the documentation was lacking or ambiguous in some specific areas..  I'm VERY relieved that this saga is over.. please feel free to close the issue.

**Comment by jims1234** [comment]
I'm going to close this issue that turned out to be in my environment Windows Desktop PC.. not sure why I had such a big problem with it and at times with my 2 alternate PC's but it finally worked and I appreciate the help Ben gave me in testing it.

**Comment by jims1234** [comment]
The only thing I wish was documented was a photo of my type of iRAngeX 4 Plus module, and a step by step procedure that shows what to expect theFlashMulti 6.1 will show a user along the way , seems like it had to update the Windows 10 and then the module drivers multiple times and as the module is switched in and out of different modes it's very hard to tell what's going wrong if there is any issue.  I now suspect some s/w or driver was blocking FlashMulti from performing but I never did find what it was .. Switching to an alternate to my backup PC for the 4th time finally started it working yet prior to that nothing worked and using a serial TTL to USB adapter and it's drivers did not help either.
